#Adds a read-only ClusterRole allowing safe viewing of cluster-level resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-cd-cluster-reader
subjects:
  - kind: ServiceAccount
    name: gitlab-runner-sa
    namespace: ci-cd
roleRef:
  kind: ClusterRole
  name: cluster-read-only
  apiGroup: rbac.authorization.k8s.io
